name: The Hartley Homestead
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bce8f1'
    - '#64b1da'
    - '#32363f'
    - '#236592'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
